#!/bin/bash

# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKER_REPO: the name of the Docker repository being built.
# DOCKERFILE_PATH: the dockerfile currently being built.
# DOCKER_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)


echo "Building '${IMAGE_NAME}'"
if [ "${DOCKER_TAG}" != "latest" ]; then
	MAVEN_VERSION=${DOCKER_TAG/#v/}
	MAVEN_BUILD_ARG="--build-arg MAVEN_VERSION=${MAVEN_VERSION}"
	MAVEN_BUILD_TAG="--tag ${DOCKER_REPO}:${MAVEN_VERSION} --tag ${DOCKER_REPO}:$(echo ${MAVEN_VERSION} | cut -d '.' -f 1)"

else
	MAVEN_VERSION=
	MAVEN_BUILD_ARG=
	MAVEN_BUILD_TAG=
fi

docker build \
	-f ${DOCKERFILE_PATH} \
	-t ${IMAGE_NAME} \
	${MAVEN_BUILD_ARG} ${MAVEN_BUILD_TAG}\
	.

# load the base images we're building over
BASE_IMAGES="$(< base-images.txt)"
for BASE_IMAGE in ${BASE_IMAGES}; do
	BASE_TAG=$(echo ${BASE_IMAGE} | cut -d ':' -f 2)

	if [ -n "$MAVEN_VERSION" ]; then
		MAVEN_BUILD_TAG="--tag ${DOCKER_REPO}:${MAVEN_VERSION}-${BASE_TAG} --tag ${DOCKER_REPO}:$(echo ${MAVEN_VERSION} | cut -d '.' -f 1)-${BASE_TAG}"
	fi
	
	echo "Building '${DOCKER_TAG}' BASE_IMAGE='${BASE_IMAGE}' MAVEN_VERSION='${MAVEN_VERSION}' TAG='${DOCKER_REPO}:${BASE_TAG}'"
	docker build \
		--build-arg BASE_IMAGE=${BASE_IMAGE} \
		-f ${DOCKERFILE_PATH} \
		-t ${DOCKER_REPO}:${BASE_TAG} \
		${MAVEN_BUILD_ARG} ${MAVEN_BUILD_TAG}\
		.
done
