#!/bin/bash


if [ ${DOCKER_TAG} != "latest" ]; then
	MAVEN_VERSION=${DOCKER_TAG/#v/}
	
	docker push ${DOCKER_REPO}:${MAVEN_VERSION}
	docker push ${DOCKER_REPO}:$(echo ${MAVEN_VERSION} | cut -d '.' -f 1)
else
	MAVEN_VERSION=
fi

# load the base images we're building over
BASE_IMAGES="$(< base-images.txt)"
for BASE_IMAGE in ${BASE_IMAGES}; do
	BASE_TAG=$(echo ${BASE_IMAGE} | cut -d ':' -f 2)

	docker push ${DOCKER_REPO}:${BASE_TAG}
	
	if [ -n "${MAVEN_VERSION}" ]; then
		docker push ${DOCKER_REPO}:${MAVEN_VERSION}-${BASE_TAG}
		docker push ${DOCKER_REPO}:$(echo ${MAVEN_VERSION} | cut -d '.' -f 1)-${BASE_TAG}
	fi
done
